version: '2'

services:
  kartographer:
    build: .
    environment:
      RABBITMQ_HOSTNAME: rabbit
    command: "npm test"
    links:
    - rabbit
    depends_on:
    - rabbit

  rabbit:
    image: rabbitmq:3-management
